services:
  fe-middleware-payment:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_APP_ENV: ${NEXT_PUBLIC_APP_ENV:-production}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8000}
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL:-http://localhost:3000}
        NEXT_PUBLIC_SOCKET_URL: ${NEXT_PUBLIC_SOCKET_URL:-http://localhost:3001}
        NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME:-Payment_Checkout}
    image: ${APP_NAME:-fe-middleware-payment}:${APP_ENV:-prod}
    container_name: ${APP_NAME:-fe-middleware-payment}-${APP_ENV:-prod}
    restart: unless-stopped
    # ports:
    #   - "${PORT:-3000}:3000"
    env_file:
      - .env
    network_mode: "host"
