name: fe_middleware_payment
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  #State Management
  get: ^4.7.2

  #Networking
  http: ^1.2.0
  socket_io_client: ^3.1.2
  connectivity_plus: ^6.1.4

  #Widget
  flutter_spinkit: ^5.2.0
  cupertino_icons: ^1.0.2
  pretty_qr_code: ^3.4.0

  #Utils
  dartz: ^0.10.1
  flutter_svg: ^2.0.9
  intl: ^0.20.2
  dynamic_path_url_strategy: ^1.0.0
  file_saver: ^0.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/payment/
    - .env
