name: fe_middleware_payment
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #State Management
  get: ^4.7.2

  #Networking
  http: ^1.2.0

  #Widget
  flutter_spinkit: ^5.2.0
  cupertino_icons: ^1.0.2

  #Utils
  dartz: ^0.10.1
  flutter_svg: ^2.0.9
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/payment/
    - .env
