import '../../feature/payment/domain/model/response/payment_category.dart';
import '../../feature/payment/domain/model/response/payment_method.dart';

List<PaymentCategory> samplePaymentCategories = [
  PaymentCategory(
    id: 1,
    key: 'va',
    title: 'Virtual Account',
    detail: 'Pembayaran melalui transfer Virtual Account Bank',
    paymentMethods: [
      PaymentResponse(
        id: 38,
        key: 'BR',
        name: 'BRIVA',
        from: 'duitku',
        bankCode: 'bri',
        type: 'va',
        category: PaymentCategory(id: 1, key: 'va', title: 'Virtual Account', detail: 'Pembayaran melalui transfer Virtual Account Bank'),
      ),
      PaymentResponse(
        id: 27,
        key: 'M2',
        name: 'Mandiri VA',
        from: 'duitku',
        bankCode: 'mandiri',
        type: 'va',
        category: PaymentCategory(id: 1, key: 'va', title: 'Virtual Account', detail: 'Pembayaran melalui transfer Virtual Account Bank'),
      ),
      PaymentResponse(
        id: 35,
        key: 'BC',
        name: 'BCA VA',
        from: 'duitku',
        bankCode: 'bca',
        type: 'va',
        category: PaymentCategory(id: 1, key: 'va', title: 'Virtual Account', detail: 'Pembayaran melalui transfer Virtual Account Bank'),
      ),
      PaymentResponse(
        id: 51,
        key: 'BN',
        name: 'BNI VA',
        from: 'duitku',
        bankCode: 'bni',
        type: 'va',
        category: PaymentCategory(id: 1, key: 'va', title: 'Virtual Account', detail: 'Pembayaran melalui transfer Virtual Account Bank'),
      ),
      PaymentResponse(
        id: 21,
        key: 'BT',
        name: 'Permata VA',
        from: 'duitku',
        bankCode: 'permata',
        type: 'va',
        category: PaymentCategory(id: 1, key: 'va', title: 'Virtual Account', detail: 'Pembayaran melalui transfer Virtual Account Bank'),
      ),
      PaymentResponse(
        id: 22,
        key: 'B1',
        name: 'CIMB Niaga VA',
        from: 'duitku',
        bankCode: 'cimb',
        type: 'va',
        category: PaymentCategory(id: 1, key: 'va', title: 'Virtual Account', detail: 'Pembayaran melalui transfer Virtual Account Bank'),
      ),
    ],
  ),
  PaymentCategory(
    id: 2,
    key: 'qris',
    title: 'QRIS',
    detail: 'Pembayaran digital melalui scan QRIS (GoPay, OVO, Dana, ShopeePay, LinkAja, dll)',
    paymentMethods: [
      PaymentResponse(
        id: 40,
        key: 'NQ',
        name: 'Nobu QRIS',
        from: 'duitku',
        bankCode: '',
        type: 'qris',
        category: PaymentCategory(id: 2, key: 'qris', title: 'QRIS', detail: 'Pembayaran digital melalui scan QRIS'),
      ),
      PaymentResponse(
        id: 29,
        key: 'SP',
        name: 'ShopeePay QRIS',
        from: 'duitku',
        bankCode: '',
        type: 'qris',
        category: PaymentCategory(id: 2, key: 'qris', title: 'QRIS', detail: 'Pembayaran digital melalui scan QRIS'),
      ),
      PaymentResponse(
        id: 48,
        key: 'DQ',
        name: 'Dana QRIS',
        from: 'duitku',
        bankCode: '',
        type: 'qris',
        category: PaymentCategory(id: 2, key: 'qris', title: 'QRIS', detail: 'Pembayaran digital melalui scan QRIS'),
      ),
    ],
  ),
  PaymentCategory(
    id: 4,
    key: 'ewallet',
    title: 'E-Wallet',
    detail: 'Pembayaran melalui dompet digital (OVO, DANA, ShopeePay, LinkAja)',
    paymentMethods: [
      PaymentResponse(
        id: 25,
        key: 'OV',
        name: 'OVO',
        from: 'duitku',
        type: 'ewallet',
      ),
      PaymentResponse(
        id: 34,
        key: 'DA',
        name: 'DANA',
        from: 'duitku',
        type: 'ewallet',
      ),
      PaymentResponse(
        id: 32,
        key: 'SA',
        name: 'SHOPEEPAY APP',
        from: 'duitku',
        type: 'ewallet',
      ),
    ],
  ),
  PaymentCategory(
    id: 3,
    key: 'cc',
    title: 'Credit Card',
    detail: 'Pembayaran instan menggunakan kartu kredit atau debit',
    paymentMethods: [
      PaymentResponse(
        id: 20,
        key: 'VC',
        name: 'Credit Card',
        from: 'duitku',
        bankCode: '',
        type: 'cc',
      ),
    ],
  ),
  PaymentCategory(
    id: 5,
    key: 'retail',
    title: 'Retail / Convenience Store',
    detail: 'Pembayaran melalui gerai retail (Indomaret, Alfamart)',
    paymentMethods: [
      PaymentResponse(
        id: 36,
        key: 'IR',
        name: 'INDOMARET',
        from: 'duitku',
        type: 'retail',
      ),
      PaymentResponse(
        id: 19,
        key: 'FT',
        name: 'RETAIL',
        from: 'duitku',
        type: 'retail',
      ),
    ],
  ),
];
